import { Navbar } from "@/src/components/navbar/navbar"
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "MOVIE | KIMO",
  description: "Generated by create next app",
};

const MovieLayout = ({ children} : {children: React.ReactNode}) => {
  return (
    <div>
      <Navbar />
      <div className="flex flex-col justify-center items-center p-10">
      {children}
      </div>
    </div>
  )
}

export default MovieLayout